name: Test

on: [pull_request]

jobs:
  validate-php:
    name: Validate
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: nanasess/setup-php@master
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Validate code against PSR12
      run: composer phpcs
    
    - name: Validate code against Psalm level 4
      run: composer psalm
  test-php:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: nanasess/setup-php@master
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run unit tests
      run: composer phpunit
